/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/satelite.glb --types
*/

import type { ThreeElements } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import type * as THREE from "three";

type GLTFResult = GLTF & {
  nodes: {
    _root: THREE.Mesh
    AO_HRMA: THREE.Mesh
    foil_gold: THREE.Mesh
    foil_silver: THREE.Mesh
    shiny_panel: THREE.Mesh
    tex_01: THREE.Mesh
  }
  materials: {
    AO_HRMA: THREE.MeshStandardMaterial
    foil_gold: THREE.MeshStandardMaterial
    foil_silver: THREE.MeshStandardMaterial
    shiny_panel: THREE.MeshStandardMaterial
    tex_01: THREE.MeshStandardMaterial
  }
};

export function Model(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF("/satelite.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._root.geometry} material={nodes._root.material}>
        <mesh geometry={nodes.AO_HRMA.geometry} material={materials.AO_HRMA} scale={[3.037, 0.522, 0.522]} />
        <mesh geometry={nodes.foil_gold.geometry} material={materials.foil_gold} />
        <mesh geometry={nodes.foil_silver.geometry} material={materials.foil_silver} />
        <mesh geometry={nodes.shiny_panel.geometry} material={materials.shiny_panel} scale={[0.025, 0.474, 0.025]} />
        <mesh geometry={nodes.tex_01.geometry} material={materials.tex_01} scale={[0.025, 0.474, 0.025]} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/satelite.glb");
